CREATE TABLE "account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "category" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"sessionId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"color" varchar(50) DEFAULT '#3b82f6' NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"maxEntriesPerPerson" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "comment" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"sessionId" varchar(255) NOT NULL,
	"ideaId" varchar(255),
	"groupId" varchar(255),
	"userId" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "idea_group" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"sessionId" varchar(255) NOT NULL,
	"categoryId" varchar(255) NOT NULL,
	"title" varchar(500),
	"order" integer DEFAULT 0 NOT NULL,
	"maxCards" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "idea" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"sessionId" varchar(255) NOT NULL,
	"categoryId" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"authorId" varchar(255),
	"isAnonymous" boolean DEFAULT true NOT NULL,
	"groupId" varchar(255),
	"order" integer DEFAULT 0 NOT NULL,
	"isSelected" boolean DEFAULT false NOT NULL,
	"priority" integer,
	"assignedToId" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "magic_session" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"ownerId" varchar(255) NOT NULL,
	"visibility" varchar(50) DEFAULT 'public' NOT NULL,
	"currentStage" varchar(100) DEFAULT 'pre_session' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "session_admin" (
	"sessionId" varchar(255) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"addedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "session_admin_sessionId_userId_pk" PRIMARY KEY("sessionId","userId")
);
--> statement-breakpoint
CREATE TABLE "session_settings" (
	"sessionId" varchar(255) PRIMARY KEY NOT NULL,
	"enablePreSession" boolean DEFAULT true NOT NULL,
	"enablePreSubmit" boolean DEFAULT false NOT NULL,
	"enableGreenRoom" boolean DEFAULT true NOT NULL,
	"votesPerUser" integer,
	"maxVotesPerIdea" integer,
	"maxVotesPerCategory" integer,
	"allowVotingOnGroups" boolean DEFAULT true NOT NULL,
	"allowVotingOnIdeas" boolean DEFAULT true NOT NULL,
	"allowGroupsInCategories" json,
	"disallowGroupsInCategories" json,
	"ideaCollectionDuration" integer,
	"votingDuration" integer,
	"customSettings" json,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_presence" (
	"sessionId" varchar(255) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"lastSeenAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	CONSTRAINT "user_presence_sessionId_userId_pk" PRIMARY KEY("sessionId","userId")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "vote" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"sessionId" varchar(255) NOT NULL,
	"categoryId" varchar(255) NOT NULL,
	"ideaId" varchar(255),
	"groupId" varchar(255),
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "category" ADD CONSTRAINT "category_sessionId_magic_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."magic_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comment" ADD CONSTRAINT "comment_sessionId_magic_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."magic_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comment" ADD CONSTRAINT "comment_ideaId_idea_id_fk" FOREIGN KEY ("ideaId") REFERENCES "public"."idea"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comment" ADD CONSTRAINT "comment_groupId_idea_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."idea_group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comment" ADD CONSTRAINT "comment_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idea_group" ADD CONSTRAINT "idea_group_sessionId_magic_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."magic_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idea_group" ADD CONSTRAINT "idea_group_categoryId_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."category"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idea" ADD CONSTRAINT "idea_sessionId_magic_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."magic_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idea" ADD CONSTRAINT "idea_categoryId_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."category"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idea" ADD CONSTRAINT "idea_authorId_user_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idea" ADD CONSTRAINT "idea_groupId_idea_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."idea_group"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idea" ADD CONSTRAINT "idea_assignedToId_user_id_fk" FOREIGN KEY ("assignedToId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "magic_session" ADD CONSTRAINT "magic_session_ownerId_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post" ADD CONSTRAINT "post_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_admin" ADD CONSTRAINT "session_admin_sessionId_magic_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."magic_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_admin" ADD CONSTRAINT "session_admin_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_settings" ADD CONSTRAINT "session_settings_sessionId_magic_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."magic_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_presence" ADD CONSTRAINT "user_presence_sessionId_magic_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."magic_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_presence" ADD CONSTRAINT "user_presence_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_sessionId_magic_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."magic_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_categoryId_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."category"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_ideaId_idea_id_fk" FOREIGN KEY ("ideaId") REFERENCES "public"."idea"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_groupId_idea_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."idea_group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "category_session_idx" ON "category" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "category_order_idx" ON "category" USING btree ("sessionId","order");--> statement-breakpoint
CREATE INDEX "comment_idea_idx" ON "comment" USING btree ("ideaId");--> statement-breakpoint
CREATE INDEX "comment_group_idx" ON "comment" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "comment_user_idx" ON "comment" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "idea_group_session_idx" ON "idea_group" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "idea_group_category_idx" ON "idea_group" USING btree ("categoryId");--> statement-breakpoint
CREATE INDEX "idea_session_idx" ON "idea" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "idea_category_idx" ON "idea" USING btree ("categoryId");--> statement-breakpoint
CREATE INDEX "idea_author_idx" ON "idea" USING btree ("authorId");--> statement-breakpoint
CREATE INDEX "idea_group_idx" ON "idea" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "idea_order_idx" ON "idea" USING btree ("categoryId","order");--> statement-breakpoint
CREATE INDEX "magic_session_owner_idx" ON "magic_session" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "magic_session_visibility_idx" ON "magic_session" USING btree ("visibility");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_admin_user_idx" ON "session_admin" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_presence_session_idx" ON "user_presence" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "vote_session_idx" ON "vote" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "vote_user_idx" ON "vote" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "vote_idea_idx" ON "vote" USING btree ("ideaId");--> statement-breakpoint
CREATE INDEX "vote_group_idx" ON "vote" USING btree ("groupId");